# Generated by Django 3.2.4 on 2021-07-09 09:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ImageField(upload_to='')),
                ('blogImage', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('blogTitle', models.CharField(max_length=200)),
                ('blogDescription', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
