# Generated by Django 3.2.4 on 2021-06-27 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameTitle', models.CharField(max_length=200)),
                ('mainDescription', models.TextField()),
                ('descriptionListOne', models.TextField(blank=True)),
                ('descriptionListTwo', models.TextField(blank=True)),
                ('descriptionListThree', models.TextField(blank=True)),
                ('descriptionListFour', models.TextField(blank=True)),
                ('minimumListOne', models.TextField()),
                ('minimumListTwo', models.TextField()),
                ('minimumListThree', models.TextField()),
                ('minimumListFour', models.TextField()),
                ('minimumListFive', models.TextField()),
                ('recommendedListOne', models.TextField()),
                ('recommendedListTwo', models.TextField()),
                ('recommendedListThree', models.TextField()),
                ('recommendedListFour', models.TextField()),
                ('recommendedListFive', models.TextField()),
                ('photo_main', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('is_trending', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
