# Generated by Django 3.2.4 on 2021-06-28 08:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mainDescription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
