# Generated by Django 3.2.4 on 2021-06-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_maindescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='descriptionListOne',
        ),
    ]
