# Generated by Django 3.2.4 on 2021-06-28 10:00

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_minimumlistone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='minimumListOne',
            new_name='minimumRequirement',
        ),
        migrations.RemoveField(
            model_name='game',
            name='descriptionListFour',
        ),
        migrations.RemoveField(
            model_name='game',
            name='descriptionListOne',
        ),
        migrations.RemoveField(
            model_name='game',
            name='descriptionListThree',
        ),
        migrations.RemoveField(
            model_name='game',
            name='descriptionListTwo',
        ),
        migrations.RemoveField(
            model_name='game',
            name='minimumListFive',
        ),
        migrations.RemoveField(
            model_name='game',
            name='minimumListFour',
        ),
        migrations.RemoveField(
            model_name='game',
            name='minimumListThree',
        ),
        migrations.RemoveField(
            model_name='game',
            name='minimumListTwo',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommendedListFive',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommendedListFour',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommendedListOne',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommendedListThree',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommendedListTwo',
        ),
        migrations.AddField(
            model_name='game',
            name='recommendedRequirement',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
