# Generated by Django 3.2.4 on 2021-07-14 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='blog_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
