# Generated by Django 3.2.4 on 2021-07-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210714_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='blog_id',
            field=models.IntegerField(),
        ),
    ]
